---
services:
  mkv_namer:
    image: mkv_namer
    build:
      dockerfile: Dockerfile
    container_name: mkv_namer
    env_file:
      - enviroment_vars.conf
    volumes:
      - "all_subtitles/:/data/all_subtitles_dir/"
      - "data/:/data/"
      # It is not recommended to mount separate volumes for RIPs and jellyfin as that results in python having to
      # copy then delete the data for rename rather than a move.
      # - "RIPs/:/data/MakeMKV_dir"
      # - "jellyfin_Shows/:/data/jellyfin_Shows"
