---
services:
  mkv_namer:
    image: mkv_namer
    build:
      dockerfile: Dockerfile
    container_name: mkv_namer
    env_file:
      - enviroment_vars.conf
    volumes:
      - "all_subtitles/:/all_subtitles_dir/"
      - "output/:/output/"
      - "RIPs/:/MakeMKV_dir"
      - "jellyfin_Shows/:/output/jellyfin_Shows"
