---

name: Linting
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - main

run-name: Pull request - ${{ github.event.pull_request.number }}
jobs:
  shellcheck:
    name: Lint - Shell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shellcheck
        uses: ludeeus/action-shellcheck@2.0.0

  dockerlint:
    name: Lint - Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
